/* eslint-disable no-console */
import { showLogger } from '@/constant/env';

/**
 * A logger function that will only logs on development
 * @param _object - The object to log
 * @param _comment - Autogenerated with `lg` snippet
 */
export default function logger(_object: unknown, _comment?: string): void {
  if (!showLogger) return;
}
